apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: 4chan-v2
  labels:
    app: auth
spec:
  selector:
    app: auth
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
  type: ClusterIP
