apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: 4chan-v2
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP
